In [10]:
import numpy as np

array = np.arange(10)
print("Array:", array)

Array: [0 1 2 3 4 5 6 7 8 9]


In [9]:
import numpy as np

my_list = [3.14, 2.17, 0, 1, 2]
array_int = np.array(my_list, dtype=int)

print("Array:", array_int)

Array: [3 2 0 1 2]


In [11]:
import numpy as np

array_3x3 = np.arange(1, 10).reshape(3, 3)
print("array:", array_3x3)

array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
import numpy as np

array = np.random.rand(4, 5)
np.set_printoptions(precision=2, suppress=True)

print("array:", array)

array: [[0.5  0.02 0.28 0.44 0.72]
 [0.27 0.71 0.99 0.89 0.6 ]
 [0.86 0.51 0.96 0.8  0.01]
 [0.8  0.28 0.91 0.42 0.32]]


In [14]:
import numpy as np

array_2d = np.array([[10, 11, 12, 13, 14],
                     [20, 21, 22, 23, 24],
                     [30, 31, 32, 33, 34]])
second_row = array_2d[1]

print("array:", second_row)

array: [20 21 22 23 24]


In [15]:
import numpy as np

array_1d = np.arange(10)
reversed_array = array_1d[::-1]

print("array:", reversed_array)

array: [9 8 7 6 5 4 3 2 1 0]


In [16]:
import numpy as np

identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_sum = np.sum(array_1d)
array_average = np.mean(array_1d)

print(f"Sum: {array_sum}, Average: {array_average}")

Sum: 55, Average: 5.5


In [18]:
import numpy as np

array = np.arange(1, 21)
array_reshaped = array.reshape(4, 5)

print(array_reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [19]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_numbers = array[array % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]
